### ISSUE TITLE
Why ErrorInfo is exported by is not presented in googleErrorDetailsTypeNameMap?

### ISSUE THREAD

**Issue by maZahaca** [quangtm210395/grpc-node-status-proto#1]
Why ErrorInfo is exported by is not presented in googleErrorDetailsTypeNameMap?

It's not possible to `addDetail` for `ErrorInfo` at the moment.

**Comment by hikariqvcce** [comment]
I will add it.

**Comment by quangtm210395** [comment]
@maZahaca The issue fixed in 1.1.6. Please try it. Thanks for your feedback.

**Comment by maZahaca** [comment]
Thank you!
